baseURL = 'https://ipco25.cs.jhu.edu/'
languageCode = 'en-us'
title = 'IPCO 2025'
theme = 'ananke'
resourceDir = "../resources"
copyright = "Mathematical Optimization Society"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

env = "production"
production = true # Set to false for development or testing environments
public = true # Set to false if the site should not be indexed
private = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.en]
    title = "IPCO 2025"
    weight = 1
    contentDir = "content"
    # languageDirection = 'rtl' for Right-To-Left languages
  

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Integer Programming and Combinatorial Optimization"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/GoHugoIO"

